spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/carero_h2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

# api 출력에 error trace를 출력하지 않음
server:
  error:
    include-stacktrace: on_param

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
