spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/carero_h2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

# api 출력에 error trace를 출력하지 않음
server:
  error:
    include-stacktrace: on_param

logging:
  level:
    com.carero: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  header: Authorization
  secret: a2JzYXQtdGVjaC1zcHJpbmctYm9vdC1qd3QtdHV0b3JpYWwtc2VjcmV0LXR1dG9yaWFsLXNlY3JldC1zcHJpbmctc2RmYXNkLWZkYWZld3Itc2RmenhjdnhjenZ4Yy1iZmRnZXRyd3QK
  token-validity-in-seconds: 3600